[package]
name = "converter"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "*", default-features = false, features = ["json", "rustls-tls"] }
tokio = { version = "1", features = ["full"] }
